package geoanalytique.gui;

import geoanalytique.model.Point;
import geoanalytique.model.Segment;
import geoanalytique.graphique.GLine;
import geoanalytique.graphique.GOvale;
import geoanalytique.graphique.Graphique;
import geoanalytique.view.GeoAnalytiqueView;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;
import java.awt.*;

public class GeoAnalytiqueGUI extends javax.swing.JFrame {

    /**
     * Creates new form GeoAnalytiqueView
     */
    GeoAnalytiqueView repereOrthogonal = new GeoAnalytiqueView(new ArrayList<>());
    public GeoAnalytiqueGUI() {
        initComponents();
        
        
        tableauDessin.setLayout(new BorderLayout());
        tableauDessin.add(repereOrthogonal, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tableauDessin = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenu();
        btnCercle = new javax.swing.JMenuItem();
        btnDroite = new javax.swing.JMenuItem();
        btnSegment = new javax.swing.JMenuItem();
        btnEllipse = new javax.swing.JMenuItem();
        btnCarre = new javax.swing.JMenuItem();
        btnClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableauDessin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tableauDessinLayout = new javax.swing.GroupLayout(tableauDessin);
        tableauDessin.setLayout(tableauDessinLayout);
        tableauDessinLayout.setHorizontalGroup(
            tableauDessinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        tableauDessinLayout.setVerticalGroup(
            tableauDessinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        jMenu1.setText("Outils");

        jMenuItem1.setText("selectionner");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("deselectionner");

        jMenu1.add(jMenuItem2);

        btnClear.setText("Effacer");
        jMenu1.add(btnClear);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jMenuBar1.add(jMenu1);

        jMenuItem3.setText("Dessiner");
        

        btnCercle.setText("Cercle");
        btnCercle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuItem3.add(btnCercle);

        btnDroite.setText("Droite");
        jMenuItem3.add(btnDroite);

        btnSegment.setText("Segment");
        jMenuItem3.add(btnSegment);

        btnEllipse.setText("Ellipse");
        jMenuItem3.add(btnEllipse);

        btnCarre.setText("Carre");
        btnCarre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarreActionPerformed(evt);
            }
        });
        jMenuItem3.add(btnCarre);

        jMenuBar1.add(jMenuItem3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tableauDessin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableauDessin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>   

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
        // Efface tous les graphiques de GeoAnalytiqueView
        repereOrthogonal.clearGraphiques();
    }

    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Créer un cercle avec des coordonnées spécifiques pour le centre et le rayon
        System.out.println( "Creation d'un Cercle" );
        Point centre = new Point(300, 300); // Coordonnées du centre
        int rayon = 100; // Rayon du cercle

        // Créer un objet GOvale avec le centre et le rayon
        GOvale cercle = new GOvale((int) centre.getAbscisse(), (int) centre.getOrdonnee(), rayon, rayon);

        // Ajouter le cercle à la liste d'objets géométriques de GeoAnalytiqueView
        List<Graphique> graphiques = new ArrayList<>();
        graphiques.add(cercle);

        // Rafraîchir l'affichage de GeoAnalytiqueView
        repereOrthogonal.setGraphiques(graphiques);
        repereOrthogonal.repaint();
    }


    private void btnCarreActionPerformed(java.awt.event.ActionEvent evt) {                                         
         // Créer un carré avec des points spécifiques
         System.out.println( "Creation d'un Carre" );
        Point p1 = new Point(50, 50); // Coin supérieur gauche
        Point p2 = new Point(100, 50); // Coin supérieur droit
        Point p3 = new Point(100, 100); // Coin inférieur droit
        Point p4 = new Point(50, 100); // Coin inférieur gauche

        // Créer les segments du carré
        Segment s1 = new Segment(p1, p2);
        Segment s2 = new Segment(p2, p3);
        Segment s3 = new Segment(p3, p4);
        Segment s4 = new Segment(p4, p1);

        // Ajouter les segments à la liste d'objets géométriques de GeoAnalytiqueView
        List<Graphique> graphiques = new ArrayList<>();
        graphiques.add(new GLine((int)s1.getPoint1().getAbscisse(), (int)s1.getPoint1().getOrdonnee(), (int)s1.getPoint2().getAbscisse(), (int)s1.getPoint2().getOrdonnee())); // Segment supérieur
        graphiques.add(new GLine((int)s2.getPoint1().getAbscisse(), (int)s2.getPoint1().getOrdonnee(), (int)s2.getPoint2().getAbscisse(), (int)s2.getPoint2().getOrdonnee())); // Segment droit
        graphiques.add(new GLine((int)s3.getPoint1().getAbscisse(), (int)s3.getPoint1().getOrdonnee(), (int)s3.getPoint2().getAbscisse(), (int)s3.getPoint2().getOrdonnee())); // Segment inférieur
        graphiques.add(new GLine((int)s4.getPoint1().getAbscisse(), (int)s4.getPoint1().getOrdonnee(), (int)s4.getPoint2().getAbscisse(), (int)s4.getPoint2().getOrdonnee())); // Segment gauche

        // Rafraîchir l'affichage de GeoAnalytiqueView
        repereOrthogonal.setGraphiques(graphiques);
        repereOrthogonal.repaint();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeoAnalytiqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeoAnalytiqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeoAnalytiqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeoAnalytiqueGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeoAnalytiqueGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem btnCarre;
    private javax.swing.JMenuItem btnClear;
    private javax.swing.JMenu jMenuItem3;
    private javax.swing.JMenuItem btnDroite;
    private javax.swing.JMenuItem btnEllipse;
    private javax.swing.JMenuItem btnSegment;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem btnCercle;
    private javax.swing.JPanel tableauDessin;
    // End of variables declaration                   
}
